# Add configuration values here, as shown below.
EMAIL: "hello@atmospheric.com.ng"
PASSWORD: "test@123"
DROPBOX_APP_KEY: "n3fxdnv8037q9ie"
DROPBOX_APP_SECRET: "7wjk5xfp41z7zkr"
DROPBOX_ACCESS_TOKEN: "kzcvfebl36mvtqj6"
DROPBOX_ACCESS_TOKEN_SECRET: "tg2gn51d4ocq8bi"
DROPBOX_USER_ID: "656103725"