development:
  adapter: postgresql
  database: atmosphericeventsng_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: atmosphericeventsng_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: atmosphericeventsng_production
  pool: 5
  timeout: 5000
